{
  "name": "Code Scanning - Action",
  "on": {
    "push": {
      "branches": [
        "main"
      ]
    },
    "pull_request": {
      "branches": [
        "main"
      ]
    },
    "schedule": [
      {
        "cron": "30 1 * * 0"
      }
    ]
  },
  "jobs": {
    "CodeQL-Build": {
      "runs-on": "ubuntu-latest",
      "permissions": {
        "security-events": "write",
        "actions": "read",
        "contents": "read"
      },
      "steps": [
        {
          "name": "Checkout repository",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Initialize CodeQL",
          "uses": "github/codeql-action/init@v2",
          "with": {
            "queries": "import csharp\n\nfrom Method m, MethodCall call, Expr flagArg, IntegerLiteral yearArg, IntegerLiteral monthArg, IntegerLiteral dayArg\nwhere\n  call.getTarget().hasQualifiedName(\"FeatureFlags\", \"IsEnabled\") and\n  call.getEnclosingCallable() = m and\n  flagArg = call.getArgument(0) and\n  yearArg = call.getArgument(1) and\n  monthArg = call.getArgument(2) and\n  dayArg = call.getArgument(3)\nselect m, m.getName(), flagArg, yearArg.getValue(), monthArg.getValue(), dayArg.getValue(), call.getLocation()\n"
          }
        },
        {
          "name": "Autobuild",
          "uses": "github/codeql-action/autobuild@v2"
        },
        {
          "name": "Perform CodeQL Analysis",
          "uses": "github/codeql-action/analyze@v2"
        }
      ]
    }
  }
}
